name: xalute
description: "Xalute platform"
publish_to: 'oslab'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  path_provider: ^2.0.11
  provider: ^6.1.2
  image_picker: ^1.0.4
  flutter_native_splash: ^2.3.5
  lottie: ^2.4.0
  flutter_date_pickers: ^0.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/xalute.png
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/xalute.png"

flutter:
  uses-material-design: true
  assets:
  - assets/icon/xalute.png
  - assets/icon/profile.png
  - assets/lottie/Animation.json

  fonts:
    - family: SeoulNam
      fonts:
        - asset: assets/fonts/seoul_nam.ttf

